### ISSUE TITLE
Update flixel-ui documentation

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#110]
Tasks:
- [ ] Inspect commits for things not mentioned
- [ ] load_if tag -- inside a tag or wrapping a block
- [ ] change tag
- [ ] "resize_label" attribute for button tag
