### ISSUE TITLE
November Goals

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#1250]
- [x] Thursday 11/17 James
  - [x] Preorder backer list of goodies
  - [x] Game scope (maps / items / monsters / etc)
  - [x] Rec letter for james
- [x] Compile & run benchmark psvita build
- [x] Roll out DQ1 controller update
  - [x] set live
  - [x] update on test_public
  - [x] make it not crash
  - [x] fix vita regressions
- [x] Figure out promotion schedule
   - [x] set discounts
   - [x] topic x
   - [x] reply to x
- [x] DQ2 skeleton script build
- [x] ~~Compile & run benchmark xbox build~~ : next month
