### ISSUE TITLE
Set up crashdumper server

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#131]
- [x] Install on test server
- [x] Successfully send http requests to crashdump server
- [x] Get adam's thumbs up
- [x] Test various kinds of crashes
