### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#1435]
- [x] Remove the "sell on purchase" checkbox
- [x] Fix the crash on startup bug
- [x] Improper skill hover text when you have 0 points
- [x] Upgrade arrows not scaling property at lower resolutions, also text is teeny
