### ISSUE TITLE
Fix progress tracker issues

### ISSUE THREAD

**Issue by codingthat** [larsiusprime/tdrpg-bugs#1585]
On http://www.defendersquest.com/2/?page=news :

- [x] Fix "Current Phase: DQ2 MILESTONE 2" since that one is now done
- [x] Create and show more phases past "MILESTONE 3" (especially since that one appears to be very nearly done) (maybe with some filler 500s, etc. as a ballpark estimate for now?)
- [x] Remove or update 404ing link to https://waffle.io/larsiusprime/tdrpg-bugs
- [x] Tell the world the tracker is fixed?  (Forum post, Steam discussion)

**Comment by larsiusprime** [comment]
Just put out this month's progress report, I'll send out a notification on the newsletter and post an update on the forum, etc, tomorrow.

**Comment by codingthat** [comment]
I replied in the Steam thread and forum post for now, anyway.  Not sure if I'm subscribed to the newsletter but it seems like something I would have subscribed to at some point...
