### ISSUE TITLE
Add auto-play mode

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#363]
- [x] Show auto-play notification
- [x] Global keyboard detect
- [x] Overworld advance
- [x] Overworld click
- [x] Map popup click
- [x] Battle instawin
- [x] Cutscene skip
- [x] Yougot skip
- [x] Reward skip
- [x] Town skip
- [ ] Transition skip
