### ISSUE TITLE
Achievement Tracker

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#389]
(For when you're done with the party screen stuff)

This can mostly be ported from the old legacy version. 

High-level tasks
-----
- [ ] Load achievements into game's memory somehow
- [ ] When the overworld is loaded, check current progress vs game-progress-triggered achievements
- [ ] Listen for achievements in the right places (battle / menu achieves, etc) for on-the-spot achievements
- [ ] When an achievement happens, show the popup notifier (if the option is set for it to do so)

In the achievements menu:
- [ ] Show which achievements are completed
- [ ] Show achievements properly by which difficulty tag the user has clicked
- [ ] Hide UI achievement object slots that are not used

Not part of this task:
- [ ] Steam/GOG achievement integration

Implementation
-----

* In DefendersQuest1 repo, there is an "achievements.xml" file that specifies data for each achievement:
    * sort order
    * string id
    * which stat it looks at
    * progress range for the stat
    * difficulty tag
    * title string (just a firetongue flag, look it up with UU.sysTxt() )
    * description tag (same thing)
* "SteamAchievementChecker" is the achievement manager in legacy
    * This and SteamAchievement.as / SteamStat.as, and all dependencies should be ported to Haxe.
    * It's not just for Steam, but it has that name b/c I'm sloppy
    * For instance: "Achievement.as" in original code has nothing to do with Steam Achievements, it's part of bonus challenges. I'm dumb. You want "SteamAchievement.as"
    * The "config:steam" blocks can be commented out for now
* For achievement popups:
    * Just create a very generic class for now 
    * A FlxUI9SliceSprite of the correct size with no graphics parameters (just default chrome), and a couple text field s attached to it and a placeholder image. 
    * Make the appearance of popups part of TDRPGState's functionality as every state should be a TDRPGState
    * Make sure to check the options value before showing a popup (Main.OMNI.options.getBool("achievements.popup") == true)

**Comment by larsiusprime** [comment]
Extra Credit for when we're done:

We should probably save achievement progress in a text file. In the old version it calculates what achievements you should have, from scratch, every time it loads the overworld and then spits out if you've achieved any new ones. This worked perfectly fine, but there were some instances when a player would "lose" achievements (like beat Hero mode, then go get a recruit). 

So we should later add data to the save file specifying the player's achievements. Perhaps even make that a separate file, but we'll deal with that after you've finished the first stuff.

**Comment by ProG4mr** [comment]
A couple of things before i tackle the achievement popups:

1 - Can i test the popups in the original game to check their appearance?
2 - Should the popup appearance be defined in a xml file?
3 - In the legacy, the achievement popups inherit an FlxGroup, should i use the same approach or use FlxUIPopup instead? If using the FlxGroup, how would i block the background events and UI?

Basically i can't see the achievements in the original game so i have no idea how they look like or how they behave, some tips on this would be helpful, thanks.

**Comment by larsiusprime** [comment]
1) I think in the original game you can edit your config.xml file, which
you can find in %APPDATA%/DefendersQuest/Local Store/

Remove the "<achievements>" tag section, or just delete the whole
config.xml file.

2) The popup appearance is pretty simple... just leave it unskinned for
now. Maybe make it a class that lets the user pass in the following things
as parameters in the constructor:

   - Achievement string id (then look up the title/body text and image
   accordingly)
   - Background image to use for the chrome (pass in a FlxUI9SliceSprite)
      - For now, make it optional, and if null, create one using new() and
      just resize it to the default size (see below)
      - Two FontDef objects (from flixel-ui) -- one to apply to the title,
   one to apply to the body

The achievement images I've put in here:

DefendersQuest1\assets\gfx\ui\achievements\
DefendersQuest1\assets\gfx\ui\achievements\hd\

*Default size of the default FlxUI9SliceSprite should be:

(whatever the size of the box in the original game is) * (FlxG.height / 600)

This will make it the same size in 800x600 mode, and scale up accordingly.

3) You should make the achivement popup inherit a FlxGroup, probably a
FlxSpriteGroup in fact. FlxUIPopup is for something that requires the user
to acknowledge something with "ok", or answer a question, this is just a
little notification that pops up in the corner and then goes away without
you having to click "okay" or anything.

Hope that helps!



On Fri, Jul 24, 2015 at 11:26 AM, TiagoLr <notifications@github.com> wrote:

> A couple of things before i tackle the achievement popups:
>
> 1 - Can i test the popups in the original game to check their appearance?
> 2 - Should the popup appearance be defined in a xml file?
> 3 - In the legacy, the achievement popups inherit an FlxGroup, should i
> use the same approach or use FlxUIPopup instead? If using the FlxGroup, how
> would i block the background events and UI?
>
> Basically i can't see the achievements in the original game so i have no
> idea how they look like or how they behave, some tips on this would be
> helpful, thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/389#issuecomment-124572856>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment]
To be clear on 2) -- don't use any xml. Just leave room for customization
in the constructor, that keeps it simple, and later I'll find the most
natural way to provide the customization data and just pass it in. Make the
two FontDefs optional, and if they are null, just don't apply them.

On Sat, Jul 25, 2015 at 1:27 PM, Lars Doucet <lars.doucet@gmail.com> wrote:

> 1) I think in the original game you can edit your config.xml file, which
> you can find in %APPDATA%/DefendersQuest/Local Store/
>
> Remove the "<achievements>" tag section, or just delete the whole
> config.xml file.
>
> 2) The popup appearance is pretty simple... just leave it unskinned for
> now. Maybe make it a class that lets the user pass in the following things
> as parameters in the constructor:
>
>    - Achievement string id (then look up the title/body text and image
>    accordingly)
>    - Background image to use for the chrome (pass in a FlxUI9SliceSprite)
>       - For now, make it optional, and if null, create one using new()
>       and just resize it to the default size (see below)
>       - Two FontDef objects (from flixel-ui) -- one to apply to the
>    title, one to apply to the body
>
> The achievement images I've put in here:
>
> DefendersQuest1\assets\gfx\ui\achievements\
> DefendersQuest1\assets\gfx\ui\achievements\hd\
>
> *Default size of the default FlxUI9SliceSprite should be:
>
> (whatever the size of the box in the original game is) * (FlxG.height /
> 600)
>
> This will make it the same size in 800x600 mode, and scale up accordingly.
>
> 3) You should make the achivement popup inherit a FlxGroup, probably a
> FlxSpriteGroup in fact. FlxUIPopup is for something that requires the user
> to acknowledge something with "ok", or answer a question, this is just a
> little notification that pops up in the corner and then goes away without
> you having to click "okay" or anything.
>
> Hope that helps!
>
>
>
> On Fri, Jul 24, 2015 at 11:26 AM, TiagoLr <notifications@github.com>
> wrote:
>
>> A couple of things before i tackle the achievement popups:
>>
>> 1 - Can i test the popups in the original game to check their appearance?
>> 2 - Should the popup appearance be defined in a xml file?
>> 3 - In the legacy, the achievement popups inherit an FlxGroup, should i
>> use the same approach or use FlxUIPopup instead? If using the FlxGroup, how
>> would i block the background events and UI?
>>
>> Basically i can't see the achievements in the original game so i have no
>> idea how they look like or how they behave, some tips on this would be
>> helpful, thanks.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/larsiusprime/tdrpg-bugs/issues/389#issuecomment-124572856>
>> .
>>
>
>
>
> --
> www.fortressofdoors.com -- Games, Art, Design
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by ProG4mr** [comment]
One more thing, how does the user clear the popup? Does the popup block the background UI components / events? I think I'll just make something generic for now then.

**Comment by larsiusprime** [comment]
Have you been able to reproduce it in DQ-legacy yet? It's just like a steam pop-up notification, it pops up briefly in one of the corners of the screen and then disappears after a few seconds, I don't believe there's a way to "clear" it without waiting, though a cancel button with an "X" in the upper right corner of it could certainly be useful.

**Comment by ProG4mr** [comment]
Okay, the achievements are animating and showing fine in the latest commit: 

![image](https://cloud.githubusercontent.com/assets/2106619/9424189/afa1d9fc-48da-11e5-966e-745c4a8fa498.png)

Two things now: 

1 - The legacy version seems to support uncompleted achievements, i did not add this feature yet, was it not discontinued?

2 - The Achievements are being initialized in OMNIData constructor, it works fine however they should be reset when there is a new game, or a game is loaded. What would be a good place to reset the achievements? I think in the legacy it happens when the title menu shows, let me know if thats ok.

**Comment by larsiusprime** [comment]
Great!

1) What do you specifically mean by "uncompleted achievements" ?

2) This sounds good. Probably the best thing is to unload achievements
whenever the player "exits" a gameplay session. The title screen is
generally a safe place to do that as that's where you get sent. Basically,
find out which state the "quit" button on the overworld takes you too, and
if there is an obvious global function associated with it
("Main.exitGameplay()" or something), put the achievements unloading
trigger there, otherwise put it on whatever scene it dumps you out into
(99.99% sure it's the title screen).

On Sat, Aug 22, 2015 at 8:39 AM, TiagoLr <notifications@github.com> wrote:

> Okay, the achievements are animating and showing fine in the latest
> commit:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/2106619/9424189/afa1d9fc-48da-11e5-966e-745c4a8fa498.png>
>
> Two things now:
>
> 1 - The legacy version seems to support uncompleted achievements, i did
> not add this feature yet, was it not discontinued?
>
> 2 - The Achievements are being initialized in OMNIData constructor, it
> works fine however they should be reset when there is a new game, or a game
> is loaded. What would be a good place to reset the achievements? I think in
> the legacy it happens when the title menu shows, let me know if thats ok.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/larsiusprime/tdrpg-bugs/issues/389#issuecomment-133704758>
> .
>



-- 
www.fortressofdoors.com -- Games, Art, Design
