### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#73]
Tasks:
- [x] Chart out milestones
- [x] Make simple JS progress bars
- [x] Backup DQ2 site
- [x] Push DQ2 site changes to github repo
- [x] Setup fresh test site
- [x] Change "news" to "progress"
- [x] Update progress page with JS progress bars
- [x] Link to waffle board / progress counter on site
- [x] Write a quick blogpost + newsletter
