### ISSUE TITLE
Update site

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#74]
Tasks:
- [x] Link latest relevant blog posts
- [x] New progress update blog post (with art, etc)
- [x] Fix broken links on leveluplabs.com
- [x] Create "progress" section on DefendersQuest2 site
