### ISSUE TITLE
Media push

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#787]
- [x] Upload youtube video
- [x] Update website w/ new screenshots
- [x] Update video embed with new video
- [x] Update hero art w/ new art
- [x] Update new presskit using doPressKit()
- [x] Remember to disable "live wires"
  - [x] gamepad
  - [x] bad resolutions
  - [x] etc
- [x] Upload to steam
  - [x] New beta branch? Beta keys? Figure something out
