### ISSUE TITLE
Final Release checklist

### ISSUE THREAD

**Issue by larsiusprime** [larsiusprime/tdrpg-bugs#968]
Build:
- [x] Disable cheat codes

Media:
- [x] Launch blog post
- [x] Launch newsletter
- [x] Launch tweets (larsiusprime & lul)
- [x] Launch facebook
- [ ] Launch reddit ads (?)
- [ ] Launch Press Release (?)

Steam feature checklist:
- [x] uncheck cloud save
- [x] check win/mac/linux/steamOS
- [x] uncheck workshop
- [x] ~~maybe list "partial" for spanish/italian/french/japanese/korean/czech/russian~~

Trailers:
- [x] What's new?
  - [x] presskit()
  - [x] youtube
  - [x] Steam / GOG
- [x] Launch trailer
  - [x] presskit()
  - [x] youtube
  - [x] Steam / GOG

Screenshots:
- [x] Website / presskit
- [x] Steam
  - [ ] Demo
- [x] GOG

Demos:
- [x] Downloadable
  - [x] Win
  - [ ] Mac
  - [ ] Linux
- [x] Browser
  - [x] ~~Flash (?)~~
  - [x] ~~HTML5 (?)~~
  - [x] note

Steam:
- [x] Windows build
  - [x] Steam integration (cheevos)
  - [x] Fresh build
  - [x] Legacy + DX launch popup
  - [x] Demo
- [x] Mac build
  - [x] Steam integration (cheevos)
  - [x] Fresh build
  - [x] Legacy + DX launch popup
  - [x] Demo
- [x] Linux build
  - [x] 32 bit
  - [x] 64 bit
  - [x] Fresh build
  - [x] Steam integration (cheevos)
  - [x] Legacy + DX launch popup
  - [x] Demo
- [x] Discount setting schedule

HUMBLE/GOG/ITCH:
- [x] Windows build
  - [x] ~~Installer~~
  - [x] ~~GOG integration (cheevos)~~
  - [x] GOG has
  - [x] HUMBLE has
  - [x] ITCH has
  - [x] Fresh
- [x] Mac build
  - [x] ~~GOG integration (cheevos)~~
  - [x] GOG has
  - [x] HUMBLE has
  - [x] ITCH has
  - [x] Fresh
- [x] Linux build
  - [x] ~~GOG integration~~
  - [x] GOG has
  - [x] HUMBLE has
  - [x] ITCH has
  - [x] Fresh
- [ ] Polish up GOG goodies
  - [ ] Character bios

Gamersgate:
- [ ] Cancel our distribution contract

Push the button:
- [x] Steam branch goes live
  - [x] Tested Windows
  - [x] Tested Mac
  - [x] Tested Linux
